baseURL = "https://neel2k.xyz/"
languageCode = "en-us"
title = "Musings on programming, tech and life."

enableRobotsTXT = true

[params]
name = "Nilesh D"
tagline = "Writing code, writing stories. Sometimes doing both."
